resources:
  repositories:
  - repository: DevOps2019
    type: git
    name: TodoList/TodoList
    endpoint: DevOps2019

variables:
- name: buildJobName
  value: 'BuildWebApp'
- name: artifactName
  value: 'todoList.WebApp'
  
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - HELP.md

jobs:
- job: ${{ variables.buildJobName }}
  pool:
    name: 'Self Hosted Windows 2019'
  steps:
  - checkout: self
  - checkout: DevOps2019
    