resources:
  repositories:
  - repository: DevOps2019Git
    type: git
    name: TodoList/TodoList
    endpoint: DevOps2019Server
  
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - TodoListWebApp/*
    exclude:
    - README.md
    - HELP.md

jobs:
- template: self/build-publish-dotnetcore.yml
  parameters:
    name: BuildWebApp
    project: "**/TodoListWebApp/*.csproj"
    buildConfiguration: "Debug"
    artifactName: "TodoList.WebApp"
    poolName: "Self Hosted Windows 2019"