name: $(Build.DefinitionName)-$(My.buildMajorVersion).$(Rev:r)
resources:
  repositories:
  - repository: TodoList
    type: git
    name: TodoList/TodoList
    endpoint: DevOps2019
    ref: iis

variables:
- name: buildJobName
  value: 'BuildWebApp'
- name: artifactName
  value: 'TodoList.WebApp'
- name: buildConfiguration
  value: 'Release'
- name: buildMajorVersion
  value: '1'
- name: buildMinorVersion
  value: '0'
- name: buildPatchVersion
  value: '1'
  
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - HELP.md

stages:
- stage: 'Build'
  jobs:
  - template: "self/build-publish-dotnetcore.yml"
    parameters:
      name: ${{ variables.buildJobName }}
      project: "**/TodoListWebApp/*.csproj"
      buildConfiguration: ${{ variables.buildConfiguration }}
      artifactName: ${{ variables.artifactName }}
      pool: 
        name: "Self Hosted Windows 2019"
      srcRepo: TodoList

- stage: 'DeployToStaging'
  dependsOn: 'Build'
  condition: succeeded()
  jobs:
  - template: "self/deploy-iis-website.yml"
    parameters:
      name: 'DeployWeAppToIIS'
      pool:
        name: 'Self Hosted Windows 2019'
      environment: 
        name: 'Staging'
        resourceName: 'mcw-dev2'
      appPoolName: 'TodoListAppPool'
      websiteName: 'TodoList'
      websitePhysicalPath: '%SystemDrive%\TodoList'
      bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8080","hostname":"mcw-dev2","sslThumbprint":"","sniFlag":false}]}'
      package: '$(Pipeline.Workspace)/${{ variables.artifactName }}/**/*.zip'