resources:
  repositories:
  - repository: TodoList
    type: git
    name: TodoList/TodoList
    endpoint: DevOps2019

variables:
- name: buildJobName
  value: 'BuildWebApp'
- name: artifactName
  value: 'TodoList.WebApp'
- name: buildConfiguration
  value: 'Release'
  
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - HELP.md

stages:
- stage: 'Build'
  jobs:
  - template: "self/build-publish-dotnetcore.yml"
    parameters:
      name: ${{ variables.buildJobName }}
      project: "**/TodoListWebApp/*.csproj"
      buildConfiguration: ${{ variables.buildConfiguration }}
      artifactName: ${{ variables.artifactName }}
      pool: 
        name: "Self Hosted Windows 2019"
      srcRepo: TodoList

- stage: 'DeployToPreProd'
  dependsOn: 'Build'
  condition: succeeded()
  jobs:
  - template: "self/deploy-iis-winrm.yml"
    parameters:
      name: 'DeployToIIS'
      pool:
        name: 'Self Hosted Windows 2019'
      environment: 'Staging'
      machineNames: $(WebServers)
      artifactName: ${{ variables.artifactName }}
      adminUserName: $(AdminUsername)
      adminPassword: $(AdminPassword)
      targetPath: 'C:\WebDeploy'