# File build-publish-dotnetcore.yml

parameters:
- name: name
  type: string
  default: ""
- name: project
  type: string
  default: ""
- name: buildConfiguration
  type: string
  default: "Release"
# The name of the artifact
- name: artifactName
  type: string
  default: "drop"
- name: pool
  type: object
  default: null
- name: srcRepo
  type: object
  default: self
  
jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - checkout: ${{ parameters.srcRepo }}
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core SDK 2.0.3'
    inputs:
      version: 2.0.3

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '${{ parameters.project }}'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '${{ parameters.project }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '${{ parameters.project }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: ${{ parameters.artifactName }}