# File build-publish-dotnetcore.yml

parameters:
- name: name
  type: string
  default: ""
- name: project
  type: string
  default: ""
- name: buildConfiguration
  type: string
  default: "Debug"
# The name of the artifact
- name: artifactName
  type: string
  default: "drop"
- name: pool
  type: object
  default: null
# The repository containing the source codes to build
- name: srcRepo
  type: object
  default: self
  
jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  workspace:
    clean: all
  steps:
  - checkout: ${{ parameters.srcRepo }}
  - task: DotNetCoreInstaller@0
    displayName: 'Use .NET Core SDK 2.0.3'
    inputs:
      version: 2.0.3

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '${{ parameters.project }}'

  - task: WhiteSource Bolt@19
    displayName: 'WhiteSource Bolt'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '${{ parameters.project }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.BinariesDirectory)'

  - template: ms-sec-dev.yml
    parameters:
      binSkimAnalyzeVerbose: true
      binSkimAnalyzeTarget: '$(Build.BinariesDirectory)\*'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: false
      projects: '${{ parameters.project }}'
      arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact'
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: ${{ parameters.artifactName }}