parameters:
- name: name
  type: string
  default: "DeployToIIS"
- name: displayName
  type: string
  default: "Deploy Web App"
- name: pool
  type: object
- name: environment
  type: object
# The name of the IIS application pool
- name: appPoolName
  type: string
# The version of the .NET Framework that is loaded by the application pool.
# If the applications assigned to this application pool do not contain managed code, 
# then select the 'No Managed Code' option from the list.
- name: dotNetVersion
  type: string
  default: 'v4.0'
  values:
  - 'v4.0'
  - 'v2.0'
  - 'No Managed Code'
# The managed pipeline mode that specifies how IIS processes requests for managed content. 
# Use classic mode only when the applications in the application pool cannot run in the Integrated mode.
- name: pipelineMode
  type: string
  default: 'Integrated'
  values:
  - 'Integrated'
  - 'Classic'
# The account under which an application pool's worker process runs. Select one of the predefined security accounts.
- name: appPoolIdentity
  type: string
  default: 'ApplicationPoolIdentity'
  values:
  - 'ApplicationPoolIdentity'
  - 'LocalService'
  - 'LocalSystem'
  - 'NetworkService'
# The name of the IIS website
- name: websiteName
  type: string
# The physical path where the website content will be stored. The content can reside on the local Computer, 
# or in a remote directory, or on a network share, like C:\Fabrikam or \\ContentShare\Fabrikam.
- name: websitePhysicalPath
  type: string
# The bindings JSON array for the website. e.g. {"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8080","hostname":"","sslThumbprint":"","sniFlag":false}]}
- name: bindings
  type: string
  default: ''
# File path to the artifact to deploy
- name: package
  type: string
# The identifier of the pipeline resource
- name: pipeline
  type: object
  default: current
# The name of the artifact to download
- name: artifactName
  type: string
  default: ''
# The pattern of the artifact(s) to download
- name: artifactPatterns
  type: string
  default: ''
# True to substitute variables in *.config file(s). 'key' or 'name' entries in the appSettings, applicationSettings, and 
# 'connectionStrings' sections of any config file and parameters.xml
- name: xmlVariableSubstitution
  type: boolean
  default: false
# New line separated list of JSON files to substitute the variable values. Files names are to be provided relative
# to the root folder. To substitute JSON variables that are nested or hierarchical, specify them using JSONPath 
# expressions.
- name: jsonFiles
  type: string
  default: ''
- name: rootDirectory
  type: string
  default: ''


jobs:
- deployment: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}
  environment: ${{ parameters.environment }}
  strategy:
    runOnce: 
      deploy:
        steps:
        - download: ${{ parameters.pipeline }}
          ${{ if gt(length(parameters.artifactName), 0) }}:
            artifact: ${{ parameters.artifactName }}
          ${{ if gt(length(parameters.artifactPatterns), 0) }}:
            patterns: ${{ parameters.artifactPatterns }}

        - ${{ if eq(parameters.xmlVariableSubstitution, true) }}:
          - task: ExtractFiles@1
            displayName: 'Extract Artifact'
            inputs:
              archiveFilePatterns: ${{ parameters.package }}
              destinationFolder: '$(Pipeline.Workspace)/${{ parameters.artifactName }}'

        - task: IISWebAppManagementOnMachineGroup@0
          displayName: 'Manage IIS Website'
          inputs:
            IISDeploymentType: 'iISWebsite'
            actionIISWebsite: 'CreateOrUpdateWebsite'
            websiteName: ${{ parameters.websiteName }}
            websitePhysicalPath: ${{ parameters.websitePhysicalPath }}
            createOrUpdateAppPoolForWebsite: true
            appPoolNameForWebsite: ${{ parameters.appPoolName }}
            dotNetVersionForWebsite: ${{ parameters.dotNetVersion }}
            pipelineModeForWebsite: ${{ parameters.pipelineMode }}
            appPoolIdentityForWebsite: ${{ parameters.appPoolIdentity }}
            ${{ if gt(length(parameters.bindings), 0) }}:
              addBinding: true
              bindings: ${{ parameters.bindings }}

        - task: IISWebAppDeploymentOnMachineGroup@0
          displayName: 'Deploy IIS Website'
          inputs:
            websiteName: ${{ parameters.websiteName }}
            package: ${{ parameters.package }}
            removeAdditionalFilesFlag: true
            takeAppOfflineFlag: true
            XmlVariableSubstitution: ${{ parameters.xmlVariableSubstitution }}
            ${{ if gt(length(parameters.jsonFiles), 0) }}:
              jsonFiles: ${{ parameters.jsonFiles }}

        - ${{ if eq(parameters.xmlVariableSubstitution, true) }}:
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace XML Tokens'
            inputs:
              ${{ if gt(length(parameters.rootDirectory), 0) }}:
                rootDirectory: ${{ parameters.rootDirectory }}
              verbosity: detailed
