# File owasp-zap.yml

parameters:
# The name of the job
- name: name
  type: string
  default: "OWASPSecurityScan"
- name: displayName
  type: string
  default: "OWASP Security Scan"
# The pool to run the job
- name: pool
  type: object
- name: dependentJobName
  type: string
  default: ''
- name: dependentCondition
  type: string
  default: ''
# The version of Docker CLI to install
- name: dockerVersion
  type: string
  default: '17.09.0-ce'
# The failure threshold that indicates the score at which the pipeline will begin to fail.
- name: owaspThreshold
  type: number
  default: 50
# The type of scan to perform
- name: owaspScanType
  type: string
  default: ''
  values:
  - 'targetedScan'
# The URL to scan. Must begin with either http:// or https://
- name: owaspScanUrl
  type: string
  default: ''
# The port to scan on the target
- name: owaspScanPort
  type: number
  default: 80

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}
  workspace:
    clean: all
  ${{ if gt(length(parameters.dependentJobName), 0) }}:
    dependsOn: ${{ parameters.dependentJobName }}
  ${{ if gt(length(parameters.dependentCondition), 0) }}:
    condition: ${{ parameters.dependentCondition }}
  steps:
  - checkout: none

  - task: DockerInstaller@0
    displayName: 'Install Docker'
    inputs:
      dockerVersion: ${{ parameters.dockerVersion }}

  - task: CSE-DevOps.zap-scanner.custom-build-release-task.owaspzap@1
    displayName: 'ZAP Scanner'
    inputs:
      threshold: ${{ parameters.owaspThreshold }}
      ${{ if gt(length(parameters.owaspScanType), 0) }}:
        scanType: ${{ parameters.owaspScanType }}
        url: ${{ parameters.owaspScanUrl }}
      port: ${{ parameters.owaspScanPort }}