# File owasp-zap.yml

parameters:
# The name of the job
- name: name
  type: string
  default: "OWASPSecurityScan"
- name: displayName
  type: string
  default: "OWASP Security Scan"
# The pool to run the job
- name: pool
  type: object
# The version of Docker CLI to install
- name: dockerVersion
  type: string
  default: '17.09.0-ce'

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}
  workspace:
    clean: all
  steps:
  - checkout: none
  
  - task: DockerInstaller@0
    displayName: 'Install Docker'
    inputs:
      dockerVersion: ${{ parameters.dockerVersion }}
