variables:
- name: artifactName
  value: 'TodoList.WebApp'
- name: artifactPatterns
  value: '**/*.zip'
- name: todoWebAppVersion
  value: '1.0.1.2'
  
resources:
  pipelines:
  - pipeline: todo-webapp
    source: \remote\ci\todo-webapp
    project: CloudWorkshopWinRM
    version: ${{ variables.todoWebAppVersion }}
    trigger:
      branches:
      - master

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - HELP.md
    include:
    - cd/*
    - self/*

stages:
- stage: 'Staging'
  jobs:
  - template: "../self/deploy-iis-website.yml"
    parameters:
      name: 'DeployTodoWebAppToIIS'
      displayName: 'Deploy Todo List WebApp'
      pool:
        name: 'Self Hosted Windows 2019'
      environment: 
        name: 'Test'
        resourceName: 'mcw-dev2'
      appPoolName: 'TodoListAppPool'
      websiteName: 'TodoList'
      websitePhysicalPath: '%SystemDrive%\TodoList'
      bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8080","hostname":"mcw-dev2","sslThumbprint":"","sniFlag":false}]}'
      pipeline: todo-webapp
      artifactName: ${{ variables.artifactName }}
      artifactPatterns: ${{ variables.artifactPatterns }}
      package: '$(Pipeline.Workspace)/${{ variables.artifactName }}/${{ variables.artifactPatterns }}'