name: $(Build.MajorVersion).$(Build.MinorVersion).$(Build.PatchVersion).$(Rev:r)
resources:
  repositories:
  - repository: TodoList
    type: git
    name: TodoList/TodoList
    endpoint: DevOps2019
    ref: iis

variables:
- name: buildJobName
  value: 'BuildWebApp'
- name: artifactName
  value: 'TodoList.WebApp'
- name: buildConfiguration
  value: 'Release'
- name: deployJobName
  value: 'DeployWeAppToIIS'
- name: Deploy.Test
  value: false
  
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - HELP.md
    include:
    - ci/iis-pipelines.yml
    - self/build-publish-dotnetcore.yml
    - self/deploy-iis-website.yml
    - self/owasp-zap.yml

stages:
- stage: 'Build'
  jobs:
  - template: "../self/build-publish-dotnetcore.yml"
    parameters:
      name: ${{ variables.buildJobName }}
      project: "**/TodoListWebApp/*.csproj"
      buildConfiguration: ${{ variables.buildConfiguration }}
      artifactName: ${{ variables.artifactName }}
      pool: 
        name: "Self Hosted Windows 2019"
      srcRepo: TodoList

- stage: 'Test'
  dependsOn: 'Build'
  condition: and(succeeded(), eq(variables['Deploy.Test'], true))
  variables:
  - template: test-variables.yml
  jobs:
  - template: "../self/deploy-iis-website.yml"
    parameters:
      name: ${{ variables.deployJobName }}
      pool:
        name: 'Self Hosted Windows 2019'
      environment: 
        name: 'Test'
        resourceName: 'mcw-dev2'
      appPoolName: 'TodoListAppPool'
      websiteName: 'TodoList'
      websitePhysicalPath: '%SystemDrive%\TodoList'
      bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"8080","sslThumbprint":"","sniFlag":false}]}'
      package: '$(Pipeline.Workspace)/${{ variables.artifactName }}/**/*.zip'
      xmlVariableSubstitution: true

  - template: '../self/owasp-zap.yml'
    parameters:
      pool:
        name: 'Self Hosted Linux'
      dependentJobName: ${{ variables.deployJobName }}
      dependentCondition: and(succeeded(), eq(variables['Deploy.Test'], true))
      owaspThreshold: 110
      owaspScanType: targetedScan
      owaspScanUrl: http://mcw-dev2
      owaspScanPort: 8080