name: $(Build.MajorVersion).$(Build.MinorVersion).$(Build.PatchVersion).$(Rev:r)
resources:
  repositories:
  - repository: TodoListService
    type: github
    name: lamst/active-directory-javascript-nodejs-webapi-v2
    endpoint: GitHub
    ref: todo
    trigger:
      branches:
        include:
        - todo

variables:
- name: buildJobName
  value: 'BuildService'
- name: artifactName
  value: 'TodoList.Service'

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - HELP.md
    include:
    - ci/nodejs-pipelines.yml
    - self/build-publish-nodejs.yml
    - self/deploy-nodejs.yml

stages:
- stage: 'Build'
  jobs:
  - template: "../self/build-publish-nodejs.yml"
    parameters:
      name: ${{ variables.buildJobName }}
      artifactName: ${{ variables.artifactName }}
      pool: 
        name: "Self Hosted Windows 2019"
      srcRepo: TodoListService

- stage: 'Test'
  dependsOn: 'Build'
  condition: and(succeeded(), eq(variables[Deploy.Test], true))
  jobs:
  - template: '../self/deploy-nodejs.yml'
    parameters:
      name: 'DeployNodeJSApp'
      pool:
        name: 'Self Hosted Windows 2019'
      environment: 
        name: 'Test'
        resourceName: 'mcw-dev2'
      artifactName: ${{ variables.artifactName }}
      package: $(Pipeline.Workspace)/${{ variables.artifactName }}
      processName: 'todo-api'
      ecosystemFilename: 'ecosystem.config.js'
      appPhysicalPath: 'C:\TodoListService'